name: Unit Tests
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - gemfile: gemfiles/rails_3.1.x.gemfile
            ruby-version: 2.2.x
          - gemfile: gemfiles/rails_3.2.x.gemfile
            ruby-version: 2.2.x
          - gemfile: gemfiles/rails_4.0.x.gemfile
            ruby-version: 2.3.x
          - gemfile: gemfiles/rails_4.1.x.gemfile
            ruby-version: 2.3.x
          - gemfile: gemfiles/rails_4.2.x.gemfile
            ruby-version: 2.5.x
          - gemfile: gemfiles/rails_5.0.x.gemfile
            ruby-version: 2.5.x
          - gemfile: gemfiles/rails_5.1.x.gemfile
            ruby-version: 2.5.x
          - gemfile: gemfiles/rails_5.2.0.gemfile
            ruby-version: 2.5.x
          - gemfile: gemfiles/rails_5.2.1.gemfile
            ruby-version: 2.5.x
          - gemfile: gemfiles/rails_6.0.x.gemfile
            ruby-version: 2.5.x
          - gemfile: gemfiles/rails_6.1.x.gemfile
            ruby-version: 2.7.x
          - gemfile: gemfiles/rails_6.1.x.gemfile
            ruby-version: 3.0.x
          - gemfile: gemfiles/rails_7.0.x.gemfile
            ruby-version: 3.0.x
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
        env:
          BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      - name: Run Tests
        run: bundle exec rspec
        env:
          BUNDLE_GEMFILE: ${{ matrix.gemfile }}
