name: Unit Tests
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - gemfile: gemfiles/rails_4.0.x.gemfile
            ruby-version: 2.3
          - gemfile: gemfiles/rails_4.1.x.gemfile
            ruby-version: 2.3
          - gemfile: gemfiles/rails_4.2.x.gemfile
            ruby-version: 2.5
          - gemfile: gemfiles/rails_5.0.x.gemfile
            ruby-version: 2.5
          - gemfile: gemfiles/rails_5.1.x.gemfile
            ruby-version: 2.5
          - gemfile: gemfiles/rails_5.2.0.gemfile
            ruby-version: 2.5
          - gemfile: gemfiles/rails_5.2.1.gemfile
            ruby-version: 2.5
          - gemfile: gemfiles/rails_6.0.x.gemfile
            ruby-version: 2.5
          - gemfile: gemfiles/rails_6.1.x.gemfile
            ruby-version: 2.7
          - gemfile: gemfiles/rails_6.1.x.gemfile
            ruby-version: 3.0
          - gemfile: gemfiles/rails_7.0.x.gemfile
            ruby-version: 3.0
          - gemfile: gemfiles/rails_7.1.x.gemfile
            ruby-version: 3.1
          - gemfile: gemfiles/rails_7.1.x.gemfile
            ruby-version: 3.2
          - gemfile: gemfiles/rails_7.2.x.gemfile
            ruby-version: 3.3
          - gemfile: gemfiles/rails_8.0.x.gemfile
            ruby-version: 3.3
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
        env:
          BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      - name: Run Tests
        run: bundle exec rspec
        env:
          BUNDLE_GEMFILE: ${{ matrix.gemfile }}
